## Travis-CI configuration for Gem-dependencies

# this pre-builds dependencies for Gem, and makes them available for later-download
#
# target architectures: osx(amd64) and osx(i386)
# deployment: the build artefacts are deployed via tags on github.com

language:

env:
  matrix:
  - ARCH=amd64 PDVERSUFFIX="-64bit"
  - ARCH=i386  PDVERSUFFIX=""
  global:
  - PDVERSION=0.46-5

os:
  - osx

before_install:
 # snapshot of /usr/local
 - ls -l /usr/local/Cellar/
 - find /usr/local -not -type d > data.exclude
install:
 # install system dependencies
 - ./brew-GemDeps.sh
 # get Pd
 - wget http://msp.ucsd.edu/Software/pd-${PDVERSION}${PDVERSUFFIX}.mac.tar.gz
 - mkdir deps
 - cd deps
 - tar -xf ../pd-${PDVERSION}${PDVERSUFFIX}.mac.tar.gz
 - chmod -R u+rXw .
 - ln -s Pd-${PDVERSION}${PDVERSUFFIX}.app Pd.app
 - cd ..

script:
 - tar -cz --file brew.tgz --directory /usr/local/Cellar freetype fribidi ftgl gettext glfw2 glfw3 glib imagemagick libffi libpng libtiff pcre sdl xz
 - tar -cz --file deps.tgz deps
 - tar -c --file "GemDeps_${TRAVIS_TAG}_${TRAVIS_OS_NAME}-${ARCH}.tar" brew.tgz deps.tgz extract-GemDeps.sh

deploy:
  provider: releases
  api_key:
    # generated with 'travis encrypt ${GITHUB_OAUTH_TOKEN}'
    secure: "OsJ+PkpRRbt1zRtnUOiRLEX3DKxymZt0K8IDoMGzt556D8jV23SOl6v/Vwf582FYOUnJPyyICO65sfaerLa8PE3+GN7nk257TIkEm21C0KF0ovlhNHQVsruEVqbQXlwiKixENtyhDKGps7eHuSdLKplhLwcdHIS/ltKkEBcvaTOmxOVDFHs20gPXZ3nU2lJcgT+iHrjyAAOFaMEo5gJH/hJKSNz+T4mPHiRWM8fTKm9giK2HvxmOL67Keo2JTinDyT1JT00OHwGsdE/81OBvMMPxg5JxzliXpfM04Prny1e9U0BswwQVwBdsw/UTuibYJVrmhvdXTlOXu5ZKgfmD2m+pS6YSMSxTYAMfqhc1BajbSlTQ8iduWQsiSTj0BlSBzD9CO4YOkECnOuu8zfXr8AAkF1Ryj2sHU+ejawT8r1LfZ7WhfXrdKwHxH/PSyz7cEZgnexUiU1F8K1TfW/vMF9XEpEQsIhRryWVbPzgJ9RKlVw4tERFEcCIqyyVC9tf90rgxncqZ7d+CgrEGh62LdD22gd8+xYjUAZvkBWV7OnT5xszBe3XacxzrLwfGQMeNXiXZmCUJT/RG96QIK6oMG8oVCLzNbfB3YhflvYQP++GjPU6xB/OhyZe/5hA/qc0/iJHp1dpCtwYNswWbCh1kgBerHzJ6zWLt7L1Xirt74mA="
  file: "GemDeps_${TRAVIS_TAG}_${TRAVIS_OS_NAME}-${ARCH}.tar"
  skip_cleanup: true
  on:
    repo: umlaeute/Gem-dependencies
    tags: true
    all_branches: true

after_script:
 - ls -lh
 - ls -l /usr/local/Cellar/
