## Travis-CI configuration for Gem-dependencies

# this pre-builds dependencies for Gem, and makes them available for later-download
#
# target architectures: osx(amd64) and osx(i386)
# deployment: the build artefacts are deployed via tags on github.com

language:
env:
  matrix:
  - ARCH=amd64 PDVERSUFFIX="-64bit"
  - ARCH=i386  PDVERSUFFIX=""
  global:
  - PDVERSION=0.46-5

os:
  - osx

before_install:
 # install system dependencies
 - brew update
 - brew install coreutils
 - brew install pkg-config gettext
 - brew link gettext --force
 - brew install fribidi --universal
 - brew install imagemagick ftgl
 - brew install sdl homebrew/versions/glfw2 homebrew/versions/glfw3
 # get Pd
 - wget http://msp.ucsd.edu/Software/pd-${PDVERSION}${PDVERSUFFIX}.mac.tar.gz
 - mkdir deps
 - cd deps
 - tar -xvf ../pd-${PDVERSION}${PDVERSUFFIX}.mac.tar.gz
 - chmod -R u+rXw .
 - ln -s Pd-${PDVERSION}${PDVERSUFFIX}.app Pd.app

script:
- true

after_success:
- find /usr/local
- find deps

## deploy tagged artefacts to github
# before_deploy:
# - "./build/travis-ci/prepare-upload.sh"

deploy:
  provider: releases
  api_key:
    # generated with 'travis encrypt ${GITHUB_OAUTH_TOKEN}'
    secure: "OsJ+PkpRRbt1zRtnUOiRLEX3DKxymZt0K8IDoMGzt556D8jV23SOl6v/Vwf582FYOUnJPyyICO65sfaerLa8PE3+GN7nk257TIkEm21C0KF0ovlhNHQVsruEVqbQXlwiKixENtyhDKGps7eHuSdLKplhLwcdHIS/ltKkEBcvaTOmxOVDFHs20gPXZ3nU2lJcgT+iHrjyAAOFaMEo5gJH/hJKSNz+T4mPHiRWM8fTKm9giK2HvxmOL67Keo2JTinDyT1JT00OHwGsdE/81OBvMMPxg5JxzliXpfM04Prny1e9U0BswwQVwBdsw/UTuibYJVrmhvdXTlOXu5ZKgfmD2m+pS6YSMSxTYAMfqhc1BajbSlTQ8iduWQsiSTj0BlSBzD9CO4YOkECnOuu8zfXr8AAkF1Ryj2sHU+ejawT8r1LfZ7WhfXrdKwHxH/PSyz7cEZgnexUiU1F8K1TfW/vMF9XEpEQsIhRryWVbPzgJ9RKlVw4tERFEcCIqyyVC9tf90rgxncqZ7d+CgrEGh62LdD22gd8+xYjUAZvkBWV7OnT5xszBe3XacxzrLwfGQMeNXiXZmCUJT/RG96QIK6oMG8oVCLzNbfB3YhflvYQP++GjPU6xB/OhyZe/5hA/qc0/iJHp1dpCtwYNswWbCh1kgBerHzJ6zWLt7L1Xirt74mA="
  file: "GemDeps-${TRAVIS_TAG}-${TRAVIS_OS_NAME}${ARCH}.tgz"
  skip_cleanup: true
  on:
    repo: umlaeute/Gem-dependencies
    tags: true
    all_branches: true
